### ISSUE TITLE
Implement system `bgnpcgn-isl-latn-latn-1968` (BGN/PCGN Roman-Script Spelling Convention -- Icelandic (1968)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#106]
This issue is to implement the transliteration system of bgnpcgn-isl-latn-latn-1968.

This system is referred in the GeoNames database as `isl_Latn2Latn_BGN_1968`, with the system title 'BGN/PCGN Roman-Script Spelling Convention -- Icelandic (1968)'.

Tests should rely on the data extracted for the `isl_Latn2Latn_BGN_1968` system in https://github.com/riboseinc/geonames-transliteration-data .

```yaml
authority_id: bgnpcgn
id: 1968
language: iso-639-2:isl
source_script: Latn
destination_script: Latn
name: BGN/PCGN Icelandic 1968 Roman-Script Spelling Convention Agreement
url: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/693794/ROMAN-SCRIPT_SPELLING_CONVENTIONS.pdf
creation_date: 1968
```
