### ISSUE TITLE
Implement system `bgnpcgn-sme-latn-latn-1984` (BGN/PCGN Roman-Script Spelling Convention -- Northern Sami (1984)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#154]
This issue is to implement the transliteration system of bgnpcgn-sme-latn-latn-1984.

This system is referred in the GeoNames database as `sme_Latn2Latn_BGN_1984`, with the system title 'BGN/PCGN Roman-Script Spelling Convention -- Northern Sami (1984)'.

Tests should rely on the data extracted for the `sme_Latn2Latn_BGN_1984` system in https://github.com/riboseinc/geonames-transliteration-data .

Metadata:
```yaml
authority_id: bgnpcgn
id: 1984
language: iso-639-2:sme
source_script: Latn
destination_script: Latn
name: BGN/PCGN Northern Sami (North Lappish) 1984 Roman-Script Spelling Convention Agreement
url: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/693794/ROMAN-SCRIPT_SPELLING_CONVENTIONS.pdf
creation_date: 1984
```
