### ISSUE TITLE
Add documentation in README on how to setup gem

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#321]
These steps need to be described:

```
      - name: Install ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install swig python3-setuptools

      - name: Install macos dependencies
        if: matrix.os == 'macos-latest'
        run: brew install swig

      - name: Install windows dependencies
        if: matrix.os == 'windows-latest'
        uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: choco install --no-progress swig

      - name: Update Sequitur
        run: |
          pip3 install setuptools numpy
          pip3 install git+https://github.com/sequitur-g2p/sequitur-g2p@9b7c505
```
