### ISSUE TITLE
Enable transliteration systems with defined "map.rules"

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#5]
Some transliteration systems involve context (i.e. not pure character replacements) where pattern matching is necessary, such as lookahead.

The "BGN/PCGN Romanization of Russian" system is one of them. Within its definition, you can see this excerpt:

```yaml
...
map:
  rules:
    - pattern: "/([ЄФІЦАаЕеИиЙйОоУуЫыЮюЯяії])\u0415/"
      result: "\\1YE"
    - pattern: "/^\u0415/"
      result: "YE"
    - pattern: "/([йьъ])\u0415/"
      result: "\\1YE"
    - pattern: "/([ЄФІЦАаЕеИиЙйОоУуЫыЮюЯяії])\u0435/"
      result: "\\1ye"
    - pattern: "/^\u0435/"
      result: "ye"
    - pattern: "/([йьъ])\u0435/"
      result: "\\1ye"

  characters:
    "\u0410": "A"
    "\u0411": "B"
    "\u0412": "V"
    ...
```

This can be easily tested using the following command:

```sh
# Transliterating Russian Cyrillic to Latin using the BGN/PCGN Romanization of Russian
interscript samples/rus-Cyrl.txt --system=bgnpcgn-rus-Cyrl-Latn-1947 --output=rus-Latn.txt
```
