### ISSUE TITLE
Implement "Northern Sámi orthography"

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#632]
Authority: Saami Council (code: `saami`)
Name: "Saami Council Northern Sámi 1979 orthography"

https://en.wikipedia.org/wiki/Northern_Sami_orthography

Spec: https://en.wikipedia.org/wiki/Northern_Sami_orthography#The_1979_orthography

```yaml
authority_id: saami
id: 1979
language: iso-639-2:sme
source_script: Latn
destination_script: Latn
name: Saami Council Northern Sámi 1979 orthography
url: https://en.wikipedia.org/wiki/Northern_Sami_orthography
creation_date: 1979
```
