### ISSUE TITLE
Implement system `bgnpcgn-deu-latn-latn-1986` (BGN/PCGN German Spelling Convention (1986)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#86]
This issue is to implement the transliteration system of bgnpcgn-deu-latn-latn-1986.

This system is referred in the GeoNames database as `deu_Latn2Latn_BGN_1986`, with the system title 'BGN/PCGN German Spelling Convention (1986)'.

Tests should rely on the data extracted for the `deu_Latn2Latn_BGN_1986` system in https://github.com/riboseinc/geonames-transliteration-data .

```yaml
authority_id: bgnpcgn
id: 2000
language: iso-639-2:deu
source_script: Latn
destination_script: Latn
name: BGN/PCGN German 2000 Roman-Script Spelling Convention Agreement
url: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/693794/ROMAN-SCRIPT_SPELLING_CONVENTIONS.pdf
creation_date: 2000
```
